---
- name: Build NFS server
  command: docker build -t core_nfs ../docker/nfs

- name: NFS container
  docker:
    name: nfs
    image: core_nfs
    state: started
    privileged: yes
    ports: ["111:111", "111:111/udp", "2049:2049", "2049:2049/udp"]
    volumes: "{{ volumes }}"

